version: '2'

services:
  mlapi:
    image: jantman/docker-zm-mlapi:devel
    restart: always
    ports:
      - 8088:80
    tmpfs:
      - /run
      - /tmp
    volumes:
      - ./data:/var/lib/zmeventnotification
      - ./mlapiconfig.EXAMPLE.ini:/etc/mlapiconfig.ini
      - ./secrets.EXAMPLE.ini:/etc/secrets.ini
